project:
  type: website
  output-dir: docs

website:
  title: "Hailey Ernest"
  navbar:
    left:
      - href: projects.qmd 
        text: Projects
      - icon: github
        href: https://github.com/HaileyErnest
format:
  html:
    theme: flatly
    css: styles.css

editor: source

